










const menu = {
    list() {
        return [
    {
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"单页数据管理",
                        "menuJump":"列表",
                        "tableName":"singleSeach"
                    }
                ],
                "menu":"单页数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
			,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"高清背景管理",
                        "menuJump":"列表",
                        "tableName":"beijing"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"高清背景收藏管理",
                        "menuJump":"列表",
                        "tableName":"beijingCollection"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"高清背景下载记录管理",
                        "menuJump":"列表",
                        "tableName":"beijingXiazaijilu"
                    }
                ],
                "menu":"高清背景管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"免扣元素管理",
                        "menuJump":"列表",
                        "tableName":"yuansu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"免扣元素收藏管理",
                        "menuJump":"列表",
                        "tableName":"yuansuCollection"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"免扣元素下载记录管理",
                        "menuJump":"列表",
                        "tableName":"yuansuXiazaijilu"
                    }
                ],
                "menu":"免扣元素管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"高清背景分类管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBeijing"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"板式管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBeijingBanshi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"高清背景格式管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryBeijingGeshi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"元素分类管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYuansu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"元素格式管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryYuansuGeshi"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"高清背景管理",
                        "menuJump":"列表",
                        "tableName":"beijing"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"高清背景收藏管理",
                        "menuJump":"列表",
                        "tableName":"beijingCollection"
                    },
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"高清背景下载记录管理",
                        "menuJump":"列表",
                        "tableName":"beijingXiazaijilu"
                    }
                ],
                "menu":"高清背景管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"免扣元素管理",
                        "menuJump":"列表",
                        "tableName":"yuansu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"免扣元素收藏管理",
                        "menuJump":"列表",
                        "tableName":"yuansuCollection"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"免扣元素下载记录管理",
                        "menuJump":"列表",
                        "tableName":"yuansuXiazaijilu"
                    }
                ],
                "menu":"免扣元素管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
